FROM node:9-alpine
## A slim image of rasa-ui with out postgres db. Expects postgres to be set up with env variables.
## docker build -f Dockerfile_slim . -t myimages/slim-rasa-ui

# RUN apt-get update

# Create app directory
WORKDIR /usr/src/app

# Installation
ADD package.json .

# --no-cache: download package index on-the-fly, no need to cleanup afterwards
# --virtual: bundle packages, remove whole bundle at once, when done
RUN apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++ \
    && yarn install \
    && apk del build-dependencies

ADD . .

EXPOSE 5001
CMD [ "node", "server/server.js" ]
